x = input("What is the first number before swapping?")
y = input("What is the second number before swapping?")
print("The first number before swapping is: " + str(x))
print("The second number before swapping is: " + str(y))
print("The first number after swapping is: " + str(y))
print("The second number after swapping is: " + str(x))